// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title Egypt United Dollar (EUSD)
/// @notice A six-decimal ERC-20-shaped test asset for the Egypt network.
///
/// The TKM-native identity is not inferred from these functions. Deployment
/// tooling must append the canonical `TKMASSET` runtime trailer generated by
/// `tkmasset_buildManifest`, using chain ID 8980 and the policy hash published
/// with this contract. The chain-level trailer is what wallets and explorers
/// verify.
contract EUSD {
    string public constant name = "Egypt United Dollar";
    string public constant symbol = "EUSD";
    uint8 public constant decimals = 6;

    uint256 public totalSupply;
    address public immutable issuer;
    bytes32 public immutable policyHash;

    mapping(address => uint256) public balanceOf;
    mapping(address => mapping(address => uint256)) public allowance;

    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);

    error NotIssuer();
    error InsufficientBalance();
    error InsufficientAllowance();

    constructor(bytes32 eusdPolicyHash) {
        issuer = msg.sender;
        policyHash = eusdPolicyHash;
    }

    function transfer(address to, uint256 value) external returns (bool) {
        _transfer(msg.sender, to, value);
        return true;
    }

    function approve(address spender, uint256 value) external returns (bool) {
        allowance[msg.sender][spender] = value;
        emit Approval(msg.sender, spender, value);
        return true;
    }

    function transferFrom(address from, address to, uint256 value) external returns (bool) {
        uint256 permitted = allowance[from][msg.sender];
        if (permitted < value) revert InsufficientAllowance();
        unchecked { allowance[from][msg.sender] = permitted - value; }
        emit Approval(from, msg.sender, allowance[from][msg.sender]);
        _transfer(from, to, value);
        return true;
    }

    function mint(address to, uint256 value) external returns (bool) {
        if (msg.sender != issuer) revert NotIssuer();
        totalSupply += value;
        balanceOf[to] += value;
        emit Transfer(address(0), to, value);
        return true;
    }

    function burn(uint256 value) external returns (bool) {
        uint256 balance = balanceOf[msg.sender];
        if (balance < value) revert InsufficientBalance();
        unchecked {
            balanceOf[msg.sender] = balance - value;
            totalSupply -= value;
        }
        emit Transfer(msg.sender, address(0), value);
        return true;
    }

    /// @notice Optional contract-facing metadata; the runtime trailer remains
    /// the authoritative chain-level identity.
    function tkmAssetKind() external pure returns (uint8) { return 1; }
    function tkmAssetPolicyHash() external view returns (bytes32) { return policyHash; }

    function _transfer(address from, address to, uint256 value) internal {
        uint256 balance = balanceOf[from];
        if (balance < value) revert InsufficientBalance();
        unchecked {
            balanceOf[from] = balance - value;
            balanceOf[to] += value;
        }
        emit Transfer(from, to, value);
    }
}
