// Copyright 2015 The go-ethereum Authors
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

package miner

import (
	"context"
	"errors"
	"fmt"
	"math/big"
	"strings"
	"sync/atomic"
	"time"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/consensus/misc/eip1559"
	"github.com/ethereum/go-ethereum/consensus/misc/eip4844"
	//	"github.com/ethereum/go-ethereum/consensus/randomx"
	"github.com/ethereum/go-ethereum/core"
	"github.com/ethereum/go-ethereum/core/state"
	"github.com/ethereum/go-ethereum/core/stateless"
	"github.com/ethereum/go-ethereum/core/txpool"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/core/vm"
	"github.com/ethereum/go-ethereum/internal/telemetry"
	"github.com/ethereum/go-ethereum/log"
	"github.com/ethereum/go-ethereum/params"
	"github.com/ethereum/go-ethereum/triedb"
	"github.com/holiman/uint256"
)

var (
	errBlockInterruptedByNewHead  = errors.New("new head arrived while building block")
	errBlockInterruptedByRecommit = errors.New("recommit interrupt while building block")
	errBlockInterruptedByTimeout  = errors.New("timeout while building block")
)

// maxBlobsPerBlock returns the maximum number of blobs per block.
func (miner *Miner) maxBlobsPerBlock(time uint64) int {
	maxBlobs := eip4844.MaxBlobsPerBlock(miner.chainConfig, time)
	if miner.config.MaxBlobsPerBlock != 0 {
		maxBlobs = miner.config.MaxBlobsPerBlock
	}
	return maxBlobs
}

// environment is the worker's current environment and holds all
// information of the sealing block generation.
type environment struct {
	signer   types.Signer
	state    *state.StateDB // apply state changes here
	tcount   int            // tx count in cycle
	size     uint64         // size of the block we are building
	gasPool  *core.GasPool  // available gas used to pack transactions
	coinbase common.Address
	evm      *vm.EVM

	header   *types.Header
	txs      []*types.Transaction
	receipts []*types.Receipt
	sidecars []*types.BlobTxSidecar
	blobs    int

	witness *stateless.Witness
}

// txFitsSize reports whether the transaction fits into the block size limit.
func (env *environment) txFitsSize(tx *types.Transaction) bool {
	return env.size+tx.Size() < params.MaxBlockSize-maxBlockSizeBufferZone
}

// discard terminates the background threads before discarding it.
func (env *environment) discard() {
	env.state.StopPrefetcher()
	if env.evm != nil {
		env.evm.Release()
	}
}

const (
	commitInterruptNone int32 = iota
	commitInterruptNewHead
	commitInterruptResubmit
	commitInterruptTimeout
)

// Block size is capped by the protocol at params.MaxBlockSize.
const maxBlockSizeBufferZone = 1_000_000

// newPayloadResult is the result of payload generation.
type newPayloadResult struct {
	err      error
	block    *types.Block
	fees     *big.Int               // total block fees
	sidecars []*types.BlobTxSidecar // collected blobs of blob transactions
	stateDB  *state.StateDB         // StateDB after executing the transactions
	receipts []*types.Receipt       // Receipts collected during construction
	requests [][]byte               // Consensus layer requests collected during block construction
	witness  *stateless.Witness     // Witness is an optional stateless proof
}

// generateParams wraps various settings for generating sealing task.
type generateParams struct {
	timestamp   uint64            // The timestamp for sealing task
	forceTime   bool              // Flag whether the given timestamp is immutable or not
	parentHash  common.Hash       // Parent block hash, empty means the latest chain head
	coinbase    common.Address    // The fee recipient address for including transaction
	random      common.Hash       // The randomness generated by beacon chain, empty before the merge
	withdrawals types.Withdrawals // List of withdrawals to include in block (shanghai field)
	beaconRoot  *common.Hash      // The beacon root (cancun field).
	slotNum     *uint64           // The slot number (amsterdam field).
	noTxs       bool              // Flag whether an empty block without any transaction is expected

	forceOverrides    bool // Flag whether we should overwrite extraData and transactions
	overrideExtraData []byte
	overrideTxs       []*types.Transaction
}

// generateWork generates a sealing block based on the given parameters.
func (miner *Miner) generateWork(ctx context.Context, genParam *generateParams, witness bool) (result *newPayloadResult) {
	ctx, span, spanEnd := telemetry.StartSpan(ctx, "miner.generateWork")
	defer func() {
		if result != nil && result.err == nil {
			span.SetAttributes(
				telemetry.Int64Attribute("txs.count", int64(len(result.block.Transactions()))),
				telemetry.Int64Attribute("gas.used", int64(result.block.GasUsed())),
				telemetry.StringAttribute("fees", result.fees.String()),
			)
		}
		if result != nil {
			spanEnd(&result.err)
		} else {
			spanEnd(nil)
		}
	}()
	work, err := miner.prepareWork(ctx, genParam, witness)
	if err != nil {
		return &newPayloadResult{err: err}
	}
	defer work.discard()

	// Check withdrawals fit max block size.
	maxBlockSize := params.MaxBlockSize - maxBlockSizeBufferZone
	if genParam.withdrawals.Size() > maxBlockSize {
		return &newPayloadResult{err: errors.New("withdrawals exceed max block size")}
	}
	work.size += uint64(genParam.withdrawals.Size())

	if !genParam.noTxs {
		if genParam.forceOverrides && len(genParam.overrideTxs) > 0 {
			for _, tx := range genParam.overrideTxs {
				work.state.SetTxContext(tx.Hash(), work.tcount)
				if err := miner.commitTransaction(ctx, work, tx); err != nil {
					return &newPayloadResult{err: err}
				}
			}
		} else {
			interrupt := new(atomic.Int32)
			timer := time.AfterFunc(miner.config.Recommit, func() {
				interrupt.Store(commitInterruptTimeout)
			})
			defer timer.Stop()

			err := miner.fillTransactions(ctx, interrupt, work)
			if errors.Is(err, errBlockInterruptedByTimeout) {
				log.Warn("Block building is interrupted", "allowance", common.PrettyDuration(miner.config.Recommit))
			}
		}
	}

	body := types.Body{
		Transactions: work.txs,
		Withdrawals:  genParam.withdrawals,
	}
	if !miner.chainConfig.IsShanghai(work.header.Number, work.header.Time) {
		if body.Withdrawals != nil {
			return &newPayloadResult{err: errors.New("unexpected withdrawals before shanghai")}
		}
	} else {
		if body.Withdrawals == nil {
			body.Withdrawals = make([]*types.Withdrawal, 0)
		}
	}

	allLogs := make([]*types.Log, 0)
	for _, r := range work.receipts {
		allLogs = append(allLogs, r.Logs...)
	}

	var requests [][]byte
	if miner.chainConfig.IsPrague(work.header.Number, work.header.Time) {
		requests = [][]byte{}
		if err := core.ParseDepositLogs(&requests, allLogs, miner.chainConfig); err != nil {
			return &newPayloadResult{err: err}
		}
		if err := core.ProcessWithdrawalQueue(&requests, work.evm); err != nil {
			return &newPayloadResult{err: err}
		}
		if err := core.ProcessConsolidationQueue(&requests, work.evm); err != nil {
			return &newPayloadResult{err: err}
		}
	}
	if requests != nil {
		reqHash := types.CalcRequestsHash(requests)
		work.header.RequestsHash = &reqHash
	}

	_, _, assembleSpanEnd := telemetry.StartSpan(ctx, "miner.AssembleBlock")
	block := core.AssembleBlock(miner.engine, miner.chain, work.header, work.state, &body, work.receipts)
	assembleSpanEnd(nil)

	return &newPayloadResult{
		block:    block,
		fees:     totalFees(block, work.receipts),
		sidecars: work.sidecars,
		stateDB:  work.state,
		receipts: work.receipts,
		requests: requests,
		witness:  work.witness,
	}
}

// prepareWork constructs the sealing task according to the given parameters.
func (miner *Miner) prepareWork(ctx context.Context, genParams *generateParams, witness bool) (result *environment, err error) {
	_, _, spanEnd := telemetry.StartSpan(ctx, "miner.prepareWork")
	defer spanEnd(&err)
	miner.confMu.RLock()
	defer miner.confMu.RUnlock()

	// Find the parent block for sealing task
	parent := miner.chain.CurrentHeader()
	if genParams.parentHash != (common.Hash{}) {
		block := miner.chain.GetBlockByHash(genParams.parentHash)
		if block == nil {
			return nil, errors.New("missing parent")
		}
		parent = block.Header()
	}

	timestamp := genParams.timestamp
	if parent.Time >= timestamp {
		if genParams.forceTime {
			return nil, fmt.Errorf("invalid timestamp, parent %d given %d", parent.Time, timestamp)
		}
		timestamp = parent.Time + 1
	}

	header := &types.Header{
		ParentHash: parent.Hash(),
		Number:     new(big.Int).Add(parent.Number, common.Big1),
		GasLimit:   core.CalcGasLimit(parent.GasLimit, miner.config.GasCeil),
		Time:       timestamp,
		Coinbase:   genParams.coinbase,
	}

	if len(miner.config.ExtraData) != 0 {
		header.Extra = miner.config.ExtraData
	}
	if genParams.forceOverrides {
		header.Extra = genParams.overrideExtraData
	}
	if genParams.random != (common.Hash{}) {
		header.MixDigest = genParams.random
	}

	if miner.chainConfig.IsLondon(header.Number) {
		header.BaseFee = eip1559.CalcBaseFee(miner.chainConfig, parent)
		if !miner.chainConfig.IsLondon(parent.Number) {
			parentGasLimit := parent.GasLimit * miner.chainConfig.ElasticityMultiplier()
			header.GasLimit = core.CalcGasLimit(parentGasLimit, miner.config.GasCeil)
		}
	}

	if err := miner.engine.Prepare(miner.chain, header); err != nil {
		log.Error("Failed to prepare header for sealing", "err", err)
		return nil, err
	}

	if miner.chainConfig.IsCancun(header.Number, header.Time) {
		var excessBlobGas uint64
		if miner.chainConfig.IsCancun(parent.Number, parent.Time) {
			excessBlobGas = eip4844.CalcExcessBlobGas(miner.chainConfig, parent, timestamp)
		}
		header.BlobGasUsed = new(uint64)
		header.ExcessBlobGas = &excessBlobGas
		header.ParentBeaconRoot = genParams.beaconRoot
	}

	if miner.chainConfig.IsAmsterdam(header.Number, header.Time) {
		if genParams.slotNum == nil {
			return nil, errors.New("no slot number set post-amsterdam")
		}
		header.SlotNumber = genParams.slotNum
	}

	env, err := miner.makeEnv(parent, header, genParams.coinbase, witness)
	if err != nil && genParams.parentHash == (common.Hash{}) && isMissingStateError(err) {
		fallbackParent := miner.findLatestHeaderWithState(parent)
		if fallbackParent != nil && fallbackParent.Hash() != parent.Hash() {
			log.Warn("Falling back to ancestor with available state for sealing", "from", parent.Number, "to", fallbackParent.Number)
			parent = fallbackParent
			header.ParentHash = parent.Hash()
			header.Number = new(big.Int).Add(parent.Number, common.Big1)
			header.GasLimit = core.CalcGasLimit(parent.GasLimit, miner.config.GasCeil)
			if miner.chainConfig.IsLondon(header.Number) {
				header.BaseFee = eip1559.CalcBaseFee(miner.chainConfig, parent)
			}
			env, err = miner.makeEnv(parent, header, genParams.coinbase, witness)
		}
	}
	if err != nil {
		log.Error("Failed to create sealing context", "err", err)
		return nil, err
	}
	if header.ParentBeaconRoot != nil {
		core.ProcessBeaconBlockRoot(*header.ParentBeaconRoot, env.evm)
	}
	if miner.chainConfig.IsPrague(header.Number, header.Time) {
		core.ProcessParentBlockHash(header.ParentHash, env.evm)
	}
	return env, nil
}

func isMissingStateError(err error) bool {
	if err == nil {
		return false
	}
	return strings.Contains(err.Error(), "missing trie node") || strings.Contains(err.Error(), "state ") && strings.Contains(err.Error(), "is not available")
}

func (miner *Miner) findLatestHeaderWithState(head *types.Header) *types.Header {
	for candidate := head; candidate != nil; {
		if _, err := miner.chain.StateAt(candidate); err == nil {
			return candidate
		}
		if candidate.Number.Sign() == 0 {
			break
		}
		candidate = miner.chain.GetHeader(candidate.ParentHash, candidate.Number.Uint64()-1)
	}
	return nil
}

// makeEnv creates a new environment for the sealing block.
func (miner *Miner) makeEnv(parent *types.Header, header *types.Header, coinbase common.Address, witness bool) (*environment, error) {
	state, err := miner.chain.StateAt(parent)
	if err != nil {
		return nil, err
	}
	var bundle *stateless.Witness
	if witness {
		bundle, err = stateless.NewWitness(header, miner.chain, false)
		if err != nil {
			return nil, err
		}
	}
	state.StartPrefetcher("miner", bundle)
	return &environment{
		signer:   types.MakeSigner(miner.chainConfig, header.Number, header.Time),
		state:    state,
		size:     uint64(header.Size()),
		coinbase: coinbase,
		gasPool:  core.NewGasPool(header.GasLimit),
		header:   header,
		witness:  state.Witness(),
		evm:      vm.NewEVM(core.NewEVMBlockContext(header, miner.chain, &coinbase), state, miner.chainConfig, vm.Config{}),
	}, nil
}

func (miner *Miner) commitTransaction(ctx context.Context, env *environment, tx *types.Transaction) (err error) {
	_, _, spanEnd := telemetry.StartSpan(ctx, "miner.commitTransaction")
	defer spanEnd(&err)
	if tx.Type() == types.BlobTxType {
		return miner.commitBlobTransaction(env, tx)
	}
	receipt, err := miner.applyTransaction(env, tx)
	if err != nil {
		return err
	}
	env.txs = append(env.txs, tx)
	env.receipts = append(env.receipts, receipt)
	env.size += tx.Size()
	env.tcount++
	return nil
}

func (miner *Miner) commitBlobTransaction(env *environment, tx *types.Transaction) error {
	sc := tx.BlobTxSidecar()
	if sc == nil {
		panic("blob transaction without blobs in miner")
	}
	maxBlobs := miner.maxBlobsPerBlock(env.header.Time)
	if env.blobs+len(sc.Blobs) > maxBlobs {
		return errors.New("max data blobs reached")
	}
	receipt, err := miner.applyTransaction(env, tx)
	if err != nil {
		return err
	}
	txNoBlob := tx.WithoutBlobTxSidecar()
	env.txs = append(env.txs, txNoBlob)
	env.receipts = append(env.receipts, receipt)
	env.sidecars = append(env.sidecars, sc)
	env.blobs += len(sc.Blobs)
	env.size += txNoBlob.Size()
	*env.header.BlobGasUsed += receipt.BlobGasUsed
	env.tcount++
	return nil
}

// applyTransaction runs the transaction.
func (miner *Miner) applyTransaction(env *environment, tx *types.Transaction) (*types.Receipt, error) {
	var (
		snap = env.state.Snapshot()
		gp   = env.gasPool.Snapshot()
	)
	receipt, err := core.ApplyTransaction(env.evm, env.gasPool, env.state, env.header, tx)
	if err != nil {
		env.state.RevertToSnapshot(snap)
		env.gasPool.Set(gp)
		return nil, err
	}
	env.header.GasUsed = env.gasPool.Used()
	return receipt, nil
}

func (miner *Miner) commitTransactions(ctx context.Context, env *environment, plainTxs, blobTxs *transactionsByPriceAndNonce, interrupt *atomic.Int32) error {
	ctx, _, spanEnd := telemetry.StartSpan(ctx, "miner.commitTransactions")
	defer spanEnd(nil)

	isCancun := miner.chainConfig.IsCancun(env.header.Number, env.header.Time)
	for {
		if interrupt != nil {
			if signal := interrupt.Load(); signal != commitInterruptNone {
				return signalToErr(signal)
			}
		}
		if env.gasPool.Gas() < params.TxGas {
			log.Trace("Not enough gas for further transactions", "have", env.gasPool, "want", params.TxGas)
			break
		}
		if !blobTxs.Empty() && env.blobs >= miner.maxBlobsPerBlock(env.header.Time) {
			log.Trace("Not enough blob space for further blob transactions")
			blobTxs.Clear()
		}
		var (
			ltx *txpool.LazyTransaction
			txs *transactionsByPriceAndNonce
		)
		pltx, ptip := plainTxs.Peek()
		bltx, btip := blobTxs.Peek()

		switch {
		case pltx == nil:
			txs, ltx = blobTxs, bltx
		case bltx == nil:
			txs, ltx = plainTxs, pltx
		default:
			if ptip.Lt(btip) {
				txs, ltx = blobTxs, bltx
			} else {
				txs, ltx = plainTxs, pltx
			}
		}
		if ltx == nil {
			break
		}
		if env.gasPool.Gas() < ltx.Gas {
			log.Trace("Not enough gas left for transaction", "hash", ltx.Hash, "left", env.gasPool.Gas(), "needed", ltx.Gas)
			txs.Pop()
			continue
		}

		if isCancun {
			left := miner.maxBlobsPerBlock(env.header.Time) - env.blobs
			if left < int(ltx.BlobGas/params.BlobTxBlobGasPerBlob) {
				log.Trace("Not enough blob space left for transaction", "hash", ltx.Hash, "left", left, "needed", ltx.BlobGas/params.BlobTxBlobGasPerBlob)
				txs.Pop()
				continue
			}
		}

		tx := ltx.Resolve()
		if tx == nil {
			log.Trace("Ignoring evicted transaction", "hash", ltx.Hash)
			txs.Pop()
			continue
		}

		if !env.txFitsSize(tx) {
			break
		}
		from, _ := types.Sender(env.signer, tx)

		if tx.Protected() && !miner.chainConfig.IsEIP155(env.header.Number) {
			log.Trace("Ignoring replay protected transaction", "hash", ltx.Hash, "eip155", miner.chainConfig.EIP155Block)
			txs.Pop()
			continue
		}
		env.state.SetTxContext(tx.Hash(), env.tcount)

		err := miner.commitTransaction(ctx, env, tx)
		switch {
		case errors.Is(err, core.ErrNonceTooLow):
			log.Trace("Skipping transaction with low nonce", "hash", ltx.Hash, "sender", from, "nonce", tx.Nonce())
			txs.Shift()

		case errors.Is(err, nil):
			txs.Shift()

		default:
			log.Debug("Transaction failed, account skipped", "hash", ltx.Hash, "err", err)
			txs.Pop()
		}
	}
	return nil
}

// fillTransactions retrieves pending transactions from the txpool and fills them into the block.
func (miner *Miner) fillTransactions(ctx context.Context, interrupt *atomic.Int32, env *environment) (err error) {
	ctx, span, spanEnd := telemetry.StartSpan(ctx, "miner.fillTransactions")
	defer spanEnd(&err)

	miner.confMu.RLock()
	tip := miner.config.GasPrice
	prio := miner.prio
	miner.confMu.RUnlock()

	filter := txpool.PendingFilter{
		MinTip: uint256.MustFromBig(tip),
	}
	if env.header.BaseFee != nil {
		filter.BaseFee = uint256.MustFromBig(env.header.BaseFee)
	}
	if env.header.ExcessBlobGas != nil {
		filter.BlobFee = uint256.MustFromBig(eip4844.CalcBlobFee(miner.chainConfig, env.header))
	}
	if miner.chainConfig.IsOsaka(env.header.Number, env.header.Time) && !miner.chainConfig.IsAmsterdam(env.header.Number, env.header.Time) {
		filter.GasLimitCap = params.MaxTxGas
	}
	filter.BlobTxs = false
	pendingPlainTxs, plainTxCount := miner.txpool.Pending(filter)

	filter.BlobTxs = true
	if miner.chainConfig.IsOsaka(env.header.Number, env.header.Time) {
		filter.BlobVersion = types.BlobSidecarVersion1
	} else {
		filter.BlobVersion = types.BlobSidecarVersion0
	}
	pendingBlobTxs, blobTxCount := miner.txpool.Pending(filter)
	span.SetAttributes(
		telemetry.Int64Attribute("pending.plain.count", int64(plainTxCount)),
		telemetry.Int64Attribute("pending.blob.count", int64(blobTxCount)),
	)

	prioPlainTxs, normalPlainTxs := make(map[common.Address][]*txpool.LazyTransaction), pendingPlainTxs
	prioBlobTxs, normalBlobTxs := make(map[common.Address][]*txpool.LazyTransaction), pendingBlobTxs

	for _, account := range prio {
		if txs := normalPlainTxs[account]; len(txs) > 0 {
			delete(normalPlainTxs, account)
			prioPlainTxs[account] = txs
		}
		if txs := normalBlobTxs[account]; len(txs) > 0 {
			delete(normalBlobTxs, account)
			prioBlobTxs[account] = txs
		}
	}
	if len(prioPlainTxs) > 0 || len(prioBlobTxs) > 0 {
		plainTxs := newTransactionsByPriceAndNonce(env.signer, prioPlainTxs, env.header.BaseFee)
		blobTxs := newTransactionsByPriceAndNonce(env.signer, prioBlobTxs, env.header.BaseFee)

		if err := miner.commitTransactions(ctx, env, plainTxs, blobTxs, interrupt); err != nil {
			return err
		}
	}
	if len(normalPlainTxs) > 0 || len(normalBlobTxs) > 0 {
		plainTxs := newTransactionsByPriceAndNonce(env.signer, normalPlainTxs, env.header.BaseFee)
		blobTxs := newTransactionsByPriceAndNonce(env.signer, normalBlobTxs, env.header.BaseFee)

		if err := miner.commitTransactions(ctx, env, plainTxs, blobTxs, interrupt); err != nil {
			return err
		}
	}
	return nil
}

// totalFees computes total consumed miner fees in Wei.
func totalFees(block *types.Block, receipts []*types.Receipt) *big.Int {
	feesWei := new(big.Int)
	for i, tx := range block.Transactions() {
		minerFee, _ := tx.EffectiveGasTip(block.BaseFee())
		feesWei.Add(feesWei, new(big.Int).Mul(new(big.Int).SetUint64(receipts[i].GasUsed), minerFee))
	}
	return feesWei
}

// signalToErr converts the interruption signal to a concrete error type for return.
func signalToErr(signal int32) error {
	switch signal {
	case commitInterruptNewHead:
		return errBlockInterruptedByNewHead
	case commitInterruptResubmit:
		return errBlockInterruptedByRecommit
	case commitInterruptTimeout:
		return errBlockInterruptedByTimeout
	default:
		panic(fmt.Errorf("undefined signal %d", signal))
	}
}

// startMiningLoop starts the main mining loop that uses engine.Seal directly
func (miner *Miner) startMiningLoop() {
	miner.wg.Add(1)
	go miner.miningLoop()
}

func (miner *Miner) miningLoop() {
	defer func() {
		miner.running.Store(false)
	}()

	for {
		select {
		case <-miner.stopCh:
			log.Debug("Mining loop stopped")
			return
		default:
			// Get work for mining
			work := miner.getWorkForMining()
			if work == nil {
				time.Sleep(100 * time.Millisecond)
				continue
			}

			// Create channels for this seal attempt
			sealResultCh := make(chan *types.Block, 1)
			sealStopCh := make(chan struct{})

			// Start sealing - the engine manages its own threads
			err := miner.engine.Seal(miner.chain, work, sealResultCh, sealStopCh)
			if err != nil {
				log.Error("Failed to start sealing", "error", err)
				close(sealStopCh)
				time.Sleep(1 * time.Second)
				continue
			}

			// Wait for a result
			select {
			case sealedBlock := <-sealResultCh:
				if sealedBlock != nil {
					miner.persistParentState(sealedBlock)
					log.Info("Block sealed successfully", "number", sealedBlock.NumberU64(), "hash", sealedBlock.Hash())
					if err := miner.SubmitWork(sealedBlock); err != nil {
						log.Error("Failed to submit sealed block", "error", err)
					}
				}
			case <-miner.stopCh:
				close(sealStopCh)
				return
			}
		}
	}
}

func (miner *Miner) persistParentState(block *types.Block) {
	chainWithTrie, ok := interface{}(miner.chain).(interface{ TrieDB() *triedb.Database })
	if !ok {
		return
	}
	parent := miner.chain.GetHeader(block.ParentHash(), block.NumberU64()-1)
	if parent == nil {
		return
	}
	if _, err := miner.chain.StateAt(parent); err != nil {
		log.Warn("Unable to load parent state for persistence", "number", parent.Number, "hash", parent.Hash(), "err", err)
		return
	}
	if err := chainWithTrie.TrieDB().Commit(parent.Root, true); err != nil {
		log.Warn("Failed to persist parent state trie", "number", parent.Number, "root", parent.Root, "err", err)
	}
}

// getWorkForMining retrieves work for mining
func (miner *Miner) getWorkForMining() *types.Block {
	pending, _, _ := miner.Pending()
	if pending == nil {
		return nil
	}
	return pending
}
